// <auto-generated />
using System;
using BikeAppApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeAppApp.Migrations
{
    [DbContext(typeof(MotoDBContext))]
    [Migration("20240603215023_AddPhotoPathToMotosikletler")]
    partial class AddPhotoPathToMotosikletler
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BikeAppApp.Models.Alicilar", b =>
                {
                    b.Property<int>("AliciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AliciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AliciId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Isim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyisim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AliciId")
                        .HasName("PK__Alicilar__E859CA3A62619D00");

                    b.ToTable("Alicilar");
                });

            modelBuilder.Entity("BikeAppApp.Models.BakimGecmisi", b =>
                {
                    b.Property<int>("BakimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BakimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakimId"), 1L, 1);

                    b.Property<DateTime?>("BakimTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("MotosikletId")
                        .HasColumnType("int")
                        .HasColumnName("MotosikletID");

                    b.Property<int?>("ServisId")
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    b.Property<string>("YapilanIslemler")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BakimId")
                        .HasName("PK__BakimGec__7227287E3F817718");

                    b.HasIndex("MotosikletId");

                    b.HasIndex("ServisId");

                    b.ToTable("BakimGecmisi");
                });

            modelBuilder.Entity("BikeAppApp.Models.BayiAlici", b =>
                {
                    b.Property<int>("BayiAliciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BayiAliciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BayiAliciId"), 1L, 1);

                    b.Property<int?>("AliciId")
                        .HasColumnType("int")
                        .HasColumnName("AliciID");

                    b.Property<int?>("BayiId")
                        .HasColumnType("int")
                        .HasColumnName("BayiID");

                    b.Property<int?>("MotosikletId")
                        .HasColumnType("int")
                        .HasColumnName("MotosikletID");

                    b.Property<DateTime?>("SatisTarihi")
                        .HasColumnType("date");

                    b.HasKey("BayiAliciId");

                    b.HasIndex("AliciId");

                    b.HasIndex("BayiId");

                    b.HasIndex("MotosikletId");

                    b.ToTable("BayiAlici");
                });

            modelBuilder.Entity("BikeAppApp.Models.Bayiler", b =>
                {
                    b.Property<int>("BayiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BayiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BayiId"), 1L, 1);

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BayiAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BayiId")
                        .HasName("PK__Bayiler__A3CE97F3A59EF5CB");

                    b.ToTable("Bayiler");
                });

            modelBuilder.Entity("BikeAppApp.Models.BayiMotosiklet", b =>
                {
                    b.Property<int>("BayiMotosikletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BayiMotosikletID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BayiMotosikletId"), 1L, 1);

                    b.Property<int?>("BayiId")
                        .HasColumnType("int")
                        .HasColumnName("BayiID");

                    b.Property<int?>("MotosikletId")
                        .HasColumnType("int")
                        .HasColumnName("MotosikletID");

                    b.HasKey("BayiMotosikletId");

                    b.HasIndex("BayiId");

                    b.HasIndex("MotosikletId");

                    b.ToTable("BayiMotosiklet");
                });

            modelBuilder.Entity("BikeAppApp.Models.Calisanlar", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CalisanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanId"), 1L, 1);

                    b.Property<int?>("CalistigiYerId")
                        .HasColumnType("int")
                        .HasColumnName("CalistigiYerID");

                    b.Property<string>("CalistigiYerTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Isim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyisim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CalisanId")
                        .HasName("PK__Calisanl__40749CB6E231DAED");

                    b.HasIndex("CalistigiYerId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("BikeAppApp.Models.Motosikletler", b =>
                {
                    b.Property<int>("MotosikletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MotosikletID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotosikletId"), 1L, 1);

                    b.Property<string>("FotoğrafYolu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MotosikletId")
                        .HasName("PK__Motosikl__0B2DE72AE1AEB247");

                    b.ToTable("Motosikletler");
                });

            modelBuilder.Entity("BikeAppApp.Models.YetkiliServi", b =>
                {
                    b.Property<int>("ServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServisId"), 1L, 1);

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServisAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServisId")
                        .HasName("PK__YetkiliS__8BED6408D577BD41");

                    b.ToTable("YetkiliServis");
                });

            modelBuilder.Entity("BikeAppApp.Models.BakimGecmisi", b =>
                {
                    b.HasOne("BikeAppApp.Models.Motosikletler", "Motosiklet")
                        .WithMany("BakimGecmisis")
                        .HasForeignKey("MotosikletId")
                        .HasConstraintName("FK__BakimGecm__Motos__412EB0B6");

                    b.HasOne("BikeAppApp.Models.YetkiliServi", "Servis")
                        .WithMany("BakimGecmisis")
                        .HasForeignKey("ServisId")
                        .HasConstraintName("FK__BakimGecm__Servi__4222D4EF");

                    b.Navigation("Motosiklet");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("BikeAppApp.Models.BayiAlici", b =>
                {
                    b.HasOne("BikeAppApp.Models.Alicilar", "Alici")
                        .WithMany("BayiAlicis")
                        .HasForeignKey("AliciId")
                        .HasConstraintName("FK__BayiAlici__Alici__49C3F6B7");

                    b.HasOne("BikeAppApp.Models.Bayiler", "Bayi")
                        .WithMany("BayiAlicis")
                        .HasForeignKey("BayiId")
                        .HasConstraintName("FK__BayiAlici__BayiI__48CFD27E");

                    b.HasOne("BikeAppApp.Models.Motosikletler", "Motosiklet")
                        .WithMany("BayiAlicis")
                        .HasForeignKey("MotosikletId")
                        .HasConstraintName("FK__BayiAlici__Motos__4AB81AF0");

                    b.Navigation("Alici");

                    b.Navigation("Bayi");

                    b.Navigation("Motosiklet");
                });

            modelBuilder.Entity("BikeAppApp.Models.BayiMotosiklet", b =>
                {
                    b.HasOne("BikeAppApp.Models.Bayiler", "Bayi")
                        .WithMany("BayiMotosiklets")
                        .HasForeignKey("BayiId")
                        .HasConstraintName("FK__BayiMotos__BayiI__44FF419A");

                    b.HasOne("BikeAppApp.Models.Motosikletler", "Motosiklet")
                        .WithMany("BayiMotosiklets")
                        .HasForeignKey("MotosikletId")
                        .HasConstraintName("FK__BayiMotos__Motos__45F365D3");

                    b.Navigation("Bayi");

                    b.Navigation("Motosiklet");
                });

            modelBuilder.Entity("BikeAppApp.Models.Calisanlar", b =>
                {
                    b.HasOne("BikeAppApp.Models.Bayiler", "CalistigiYer")
                        .WithMany("Calisanlars")
                        .HasForeignKey("CalistigiYerId")
                        .HasConstraintName("FK__Calisanla__Calis__4BAC3F29");

                    b.HasOne("BikeAppApp.Models.YetkiliServi", "CalistigiYerNavigation")
                        .WithMany("Calisanlars")
                        .HasForeignKey("CalistigiYerId")
                        .HasConstraintName("FK__Calisanla__Calis__4CA06362");

                    b.Navigation("CalistigiYer");

                    b.Navigation("CalistigiYerNavigation");
                });

            modelBuilder.Entity("BikeAppApp.Models.Alicilar", b =>
                {
                    b.Navigation("BayiAlicis");
                });

            modelBuilder.Entity("BikeAppApp.Models.Bayiler", b =>
                {
                    b.Navigation("BayiAlicis");

                    b.Navigation("BayiMotosiklets");

                    b.Navigation("Calisanlars");
                });

            modelBuilder.Entity("BikeAppApp.Models.Motosikletler", b =>
                {
                    b.Navigation("BakimGecmisis");

                    b.Navigation("BayiAlicis");

                    b.Navigation("BayiMotosiklets");
                });

            modelBuilder.Entity("BikeAppApp.Models.YetkiliServi", b =>
                {
                    b.Navigation("BakimGecmisis");

                    b.Navigation("Calisanlars");
                });
#pragma warning restore 612, 618
        }
    }
}
